/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Sistemas01
 */
public class VentanaInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());

    /**
     * Creates new form VistaTAreas
     */
    public VentanaInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        promedio = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        totalEnEspera = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        totalAtendidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 6, 0, new java.awt.Color(204, 204, 204)));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 51, 51));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("INFORMACIÓN DETALLADA");
        label1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 51)));
        label1.setFocusable(false);
        bg.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 350, 50));

        promedio.setBackground(new java.awt.Color(1, 5, 86));
        promedio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        promedio.setForeground(new java.awt.Color(48, 49, 67));
        promedio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        promedio.setText("0 s");
        bg.add(promedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 80, 30));

        label2.setBackground(new java.awt.Color(1, 5, 86));
        label2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label2.setForeground(new java.awt.Color(48, 49, 67));
        label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/time.png"))); // NOI18N
        label2.setText("Promedio de atención");
        bg.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, 30));

        label.setBackground(new java.awt.Color(1, 5, 86));
        label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label.setForeground(new java.awt.Color(48, 49, 67));
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/person.png"))); // NOI18N
        label.setText("Clientes en espera");
        bg.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 30));

        totalEnEspera.setBackground(new java.awt.Color(1, 5, 86));
        totalEnEspera.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        totalEnEspera.setForeground(new java.awt.Color(48, 49, 67));
        totalEnEspera.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalEnEspera.setText("10");
        bg.add(totalEnEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 80, 30));

        label3.setBackground(new java.awt.Color(1, 5, 86));
        label3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label3.setForeground(new java.awt.Color(48, 49, 67));
        label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/person.png"))); // NOI18N
        label3.setText("Clientes atendidos");
        bg.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 230, 30));

        totalAtendidos.setBackground(new java.awt.Color(1, 5, 86));
        totalAtendidos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        totalAtendidos.setForeground(new java.awt.Color(48, 49, 67));
        totalAtendidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalAtendidos.setText("10");
        bg.add(totalAtendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel promedio;
    private javax.swing.JLabel totalAtendidos;
    private javax.swing.JLabel totalEnEspera;
    // End of variables declaration//GEN-END:variables
    public JLabel getTotalEnEspera() {
        return totalEnEspera;
    }
    public JLabel getTotalAtendidos() {
        return totalAtendidos;
    }
    public JLabel getPromedio() {
        return promedio;
    }
}
