/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Sistemas01
 */
public class Vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());

    /**
     * Creates new form VistaTAreas
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        tabla = new javax.swing.JPanel();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        f1 = new javax.swing.JPanel();
        f12 = new javax.swing.JLabel();
        f11 = new javax.swing.JLabel();
        f13 = new javax.swing.JLabel();
        f2 = new javax.swing.JPanel();
        f22 = new javax.swing.JLabel();
        f21 = new javax.swing.JLabel();
        f23 = new javax.swing.JLabel();
        f3 = new javax.swing.JPanel();
        f32 = new javax.swing.JLabel();
        f33 = new javax.swing.JLabel();
        f31 = new javax.swing.JLabel();
        f4 = new javax.swing.JPanel();
        f42 = new javax.swing.JLabel();
        f41 = new javax.swing.JLabel();
        f43 = new javax.swing.JLabel();
        f5 = new javax.swing.JPanel();
        f52 = new javax.swing.JLabel();
        f51 = new javax.swing.JLabel();
        f53 = new javax.swing.JLabel();
        f6 = new javax.swing.JPanel();
        f62 = new javax.swing.JLabel();
        f61 = new javax.swing.JLabel();
        f63 = new javax.swing.JLabel();
        f7 = new javax.swing.JPanel();
        f72 = new javax.swing.JLabel();
        f71 = new javax.swing.JLabel();
        f73 = new javax.swing.JLabel();
        f8 = new javax.swing.JPanel();
        f82 = new javax.swing.JLabel();
        f81 = new javax.swing.JLabel();
        f83 = new javax.swing.JLabel();
        nav = new javax.swing.JPanel();
        btnObtenerActual = new javax.swing.JButton();
        cmbPanelTabla = new javax.swing.JPanel();
        cmbLabelTabla = new javax.swing.JLabel();
        btnAtender = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbPanelTipoSolicitud = new javax.swing.JPanel();
        cmbLabelTipoSolicitud = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelNombre = new javax.swing.JPanel();
        inputNombre = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        checkbox = new javax.swing.JCheckBox();
        info = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelPaginacion = new javax.swing.JPanel();
        pagina = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JLabel();
        eliminar = new javax.swing.JLabel();
        panelBuscar = new javax.swing.JPanel();
        inputBuscar = new javax.swing.JTextField();
        lupa = new javax.swing.JLabel();
        deshacer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setForeground(new java.awt.Color(240, 240, 240));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setBackground(new java.awt.Color(0, 51, 51));

        c1.setBackground(new java.awt.Color(0, 51, 51));
        c1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1.setText("CLIENTE");
        c1.setFocusable(false);
        c1.setOpaque(true);

        c2.setBackground(new java.awt.Color(0, 102, 102));
        c2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c2.setText("PRIORIDAD");
        c2.setFocusable(false);
        c2.setOpaque(true);

        c3.setBackground(new java.awt.Color(0, 102, 102));
        c3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c3.setText("SOLICITUD");
        c3.setFocusable(false);
        c3.setOpaque(true);

        f1.setBackground(new java.awt.Color(255, 255, 255));
        f1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f12.setBackground(new java.awt.Color(255, 255, 255));
        f12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f12.setForeground(new java.awt.Color(51, 51, 51));
        f12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f12.setFocusable(false);
        f1.add(f12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 130, 40));

        f11.setBackground(new java.awt.Color(255, 255, 255));
        f11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f11.setForeground(new java.awt.Color(51, 51, 51));
        f11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f11.setFocusable(false);
        f1.add(f11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        f13.setBackground(new java.awt.Color(255, 255, 255));
        f13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f13.setForeground(new java.awt.Color(51, 51, 51));
        f13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f13.setFocusable(false);
        f1.add(f13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 160, 40));

        f2.setBackground(new java.awt.Color(255, 255, 255));
        f2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f22.setBackground(new java.awt.Color(255, 255, 255));
        f22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f22.setForeground(new java.awt.Color(51, 51, 51));
        f22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f22.setFocusable(false);
        f2.add(f22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 130, 40));

        f21.setBackground(new java.awt.Color(255, 255, 255));
        f21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f21.setForeground(new java.awt.Color(51, 51, 51));
        f21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f21.setFocusable(false);
        f2.add(f21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        f23.setBackground(new java.awt.Color(255, 255, 255));
        f23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f23.setForeground(new java.awt.Color(51, 51, 51));
        f23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f23.setFocusable(false);
        f2.add(f23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 160, 40));

        f3.setBackground(new java.awt.Color(255, 255, 255));
        f3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f32.setBackground(new java.awt.Color(255, 255, 255));
        f32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f32.setForeground(new java.awt.Color(51, 51, 51));
        f32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f32.setFocusable(false);
        f3.add(f32, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 130, 40));

        f33.setBackground(new java.awt.Color(255, 255, 255));
        f33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f33.setForeground(new java.awt.Color(51, 51, 51));
        f33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f33.setFocusable(false);
        f3.add(f33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 160, 40));

        f31.setBackground(new java.awt.Color(255, 255, 255));
        f31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f31.setForeground(new java.awt.Color(51, 51, 51));
        f31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f31.setFocusable(false);
        f3.add(f31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        f4.setBackground(new java.awt.Color(255, 255, 255));
        f4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f42.setBackground(new java.awt.Color(255, 255, 255));
        f42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f42.setForeground(new java.awt.Color(51, 51, 51));
        f42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f42.setFocusable(false);
        f4.add(f42, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 130, 40));

        f41.setBackground(new java.awt.Color(255, 255, 255));
        f41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f41.setForeground(new java.awt.Color(51, 51, 51));
        f41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f41.setFocusable(false);
        f4.add(f41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        f43.setBackground(new java.awt.Color(255, 255, 255));
        f43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f43.setForeground(new java.awt.Color(51, 51, 51));
        f43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f43.setFocusable(false);
        f4.add(f43, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 160, 40));

        f5.setBackground(new java.awt.Color(255, 255, 255));
        f5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f52.setBackground(new java.awt.Color(255, 255, 255));
        f52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f52.setForeground(new java.awt.Color(51, 51, 51));
        f52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f52.setFocusable(false);
        f5.add(f52, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 130, 40));

        f51.setBackground(new java.awt.Color(255, 255, 255));
        f51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f51.setForeground(new java.awt.Color(51, 51, 51));
        f51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f51.setFocusable(false);
        f5.add(f51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        f53.setBackground(new java.awt.Color(255, 255, 255));
        f53.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f53.setForeground(new java.awt.Color(51, 51, 51));
        f53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f53.setFocusable(false);
        f5.add(f53, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 160, 40));

        f6.setBackground(new java.awt.Color(255, 255, 255));
        f6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f62.setBackground(new java.awt.Color(255, 255, 255));
        f62.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f62.setForeground(new java.awt.Color(51, 51, 51));
        f62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f62.setFocusable(false);
        f6.add(f62, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 130, 40));

        f61.setBackground(new java.awt.Color(255, 255, 255));
        f61.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f61.setForeground(new java.awt.Color(51, 51, 51));
        f61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f61.setFocusable(false);
        f6.add(f61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        f63.setBackground(new java.awt.Color(255, 255, 255));
        f63.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f63.setForeground(new java.awt.Color(51, 51, 51));
        f63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f63.setFocusable(false);
        f6.add(f63, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 160, 40));

        f7.setBackground(new java.awt.Color(255, 255, 255));
        f7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f72.setBackground(new java.awt.Color(255, 255, 255));
        f72.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f72.setForeground(new java.awt.Color(51, 51, 51));
        f72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f72.setFocusable(false);
        f7.add(f72, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 130, 40));

        f71.setBackground(new java.awt.Color(255, 255, 255));
        f71.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f71.setForeground(new java.awt.Color(51, 51, 51));
        f71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f71.setFocusable(false);
        f7.add(f71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        f73.setBackground(new java.awt.Color(255, 255, 255));
        f73.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f73.setForeground(new java.awt.Color(51, 51, 51));
        f73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f73.setFocusable(false);
        f7.add(f73, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 160, 40));

        f8.setBackground(new java.awt.Color(255, 255, 255));
        f8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f82.setBackground(new java.awt.Color(255, 255, 255));
        f82.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f82.setForeground(new java.awt.Color(51, 51, 51));
        f82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f82.setFocusable(false);
        f8.add(f82, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 130, 40));

        f81.setBackground(new java.awt.Color(255, 255, 255));
        f81.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f81.setForeground(new java.awt.Color(51, 51, 51));
        f81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f81.setFocusable(false);
        f8.add(f81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        f83.setBackground(new java.awt.Color(255, 255, 255));
        f83.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f83.setForeground(new java.awt.Color(51, 51, 51));
        f83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f83.setFocusable(false);
        f8.add(f83, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 160, 40));

        javax.swing.GroupLayout tablaLayout = new javax.swing.GroupLayout(tabla);
        tabla.setLayout(tablaLayout);
        tablaLayout.setHorizontalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaLayout.createSequentialGroup()
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(f5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(f6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(f7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(f8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        tablaLayout.setVerticalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaLayout.createSequentialGroup()
                .addGroup(tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(f5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(f6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(f7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(f8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 470, 370));

        nav.setBackground(new java.awt.Color(0, 102, 102));

        btnObtenerActual.setBackground(new java.awt.Color(204, 255, 204));
        btnObtenerActual.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnObtenerActual.setForeground(new java.awt.Color(204, 255, 204));
        btnObtenerActual.setText("ACTUAL ATENDIENDOSE");
        btnObtenerActual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 2, true));
        btnObtenerActual.setContentAreaFilled(false);
        btnObtenerActual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnObtenerActual.setFocusPainted(false);
        btnObtenerActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerActualActionPerformed(evt);
            }
        });

        cmbPanelTabla.setBackground(new java.awt.Color(0, 51, 51));
        cmbPanelTabla.setForeground(new java.awt.Color(204, 255, 204));
        cmbPanelTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbPanelTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbLabelTabla.setBackground(new java.awt.Color(70, 73, 74));
        cmbLabelTabla.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cmbLabelTabla.setForeground(new java.awt.Color(204, 255, 204));
        cmbLabelTabla.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmbLabelTabla.setText("▶");
        cmbLabelTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbLabelTabla.setFocusable(false);
        cmbPanelTabla.add(cmbLabelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        btnAtender.setBackground(new java.awt.Color(204, 255, 204));
        btnAtender.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAtender.setForeground(new java.awt.Color(0, 51, 51));
        btnAtender.setText("ATENDER CLIENTE");
        btnAtender.setBorder(null);
        btnAtender.setContentAreaFilled(false);
        btnAtender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtender.setFocusPainted(false);
        btnAtender.setOpaque(true);
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(254, 254, 254));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gestión");

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");

        cmbPanelTipoSolicitud.setBackground(new java.awt.Color(0, 102, 102));
        cmbPanelTipoSolicitud.setForeground(new java.awt.Color(204, 255, 204));
        cmbPanelTipoSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbPanelTipoSolicitud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbLabelTipoSolicitud.setBackground(new java.awt.Color(70, 73, 74));
        cmbLabelTipoSolicitud.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cmbLabelTipoSolicitud.setForeground(new java.awt.Color(204, 255, 204));
        cmbLabelTipoSolicitud.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmbLabelTipoSolicitud.setText("▶");
        cmbLabelTipoSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbLabelTipoSolicitud.setFocusable(false);
        cmbPanelTipoSolicitud.add(cmbLabelTipoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Tipo de Solicitud");

        panelNombre.setBackground(new java.awt.Color(0, 102, 102));
        panelNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 204)));
        panelNombre.setOpaque(false);

        inputNombre.setBackground(new java.awt.Color(0, 51, 51));
        inputNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNombre.setForeground(new java.awt.Color(204, 255, 204));
        inputNombre.setText("Nombre del Cliente");
        inputNombre.setBorder(null);
        inputNombre.setCaretColor(new java.awt.Color(236, 255, 117));
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNombreLayout = new javax.swing.GroupLayout(panelNombre);
        panelNombre.setLayout(panelNombreLayout);
        panelNombreLayout.setHorizontalGroup(
            panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputNombre)
                .addContainerGap())
        );
        panelNombreLayout.setVerticalGroup(
            panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNombreLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 51, 51));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setOpaque(true);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        checkbox.setBackground(new java.awt.Color(0, 51, 51));
        checkbox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        checkbox.setForeground(new java.awt.Color(204, 255, 204));
        checkbox.setText("URGENTE");
        checkbox.setBorder(null);
        checkbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkbox.setFocusPainted(false);
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbPanelTipoSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(panelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPanelTipoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkbox)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        info.setBackground(new java.awt.Color(0, 51, 51));
        info.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        info.setForeground(new java.awt.Color(0, 51, 51));
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(navLayout.createSequentialGroup()
                        .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(btnObtenerActual, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(btnAtender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(navLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(cmbPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObtenerActual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 260, 590));

        jLabel9.setBackground(new java.awt.Color(0, 51, 51));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(48, 49, 67));
        jLabel9.setText("TechClassUC");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, -1));

        jLabel8.setBackground(new java.awt.Color(0, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Sitema de atención");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 20));

        panelPaginacion.setBackground(new java.awt.Color(204, 204, 204));
        panelPaginacion.setForeground(new java.awt.Color(149, 149, 149));
        panelPaginacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPaginacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pagina.setBackground(new java.awt.Color(70, 73, 74));
        pagina.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        pagina.setForeground(new java.awt.Color(0, 51, 51));
        pagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagina.setText("1/1");
        pagina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pagina.setFocusable(false);
        panelPaginacion.add(pagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 30));

        btnSiguiente.setBackground(new java.awt.Color(70, 73, 74));
        btnSiguiente.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(149, 149, 149));
        btnSiguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSiguiente.setText(" ▶");
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.setFocusable(false);
        panelPaginacion.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 40, 30));

        btnAnterior.setBackground(new java.awt.Color(70, 73, 74));
        btnAnterior.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(149, 149, 149));
        btnAnterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAnterior.setText("◀ ");
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.setFocusable(false);
        panelPaginacion.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        bg.add(panelPaginacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 100, 30));

        eliminar.setBackground(new java.awt.Color(1, 5, 86));
        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eliminar.setForeground(new java.awt.Color(149, 149, 149));
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 120, 30));

        panelBuscar.setBackground(new java.awt.Color(190, 190, 190));
        panelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputBuscar.setBackground(new java.awt.Color(190, 190, 190));
        inputBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputBuscar.setForeground(new java.awt.Color(0, 51, 51));
        inputBuscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputBuscar.setText("Buscar");
        inputBuscar.setBorder(null);
        inputBuscar.setCaretColor(new java.awt.Color(0, 51, 0));
        inputBuscar.setOpaque(true);
        inputBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBuscarActionPerformed(evt);
            }
        });
        panelBuscar.add(inputBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 140, 30));

        lupa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        lupa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBuscar.add(lupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 40, 30));

        bg.add(panelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 200, -1));

        deshacer.setBackground(new java.awt.Color(1, 5, 86));
        deshacer.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        deshacer.setForeground(new java.awt.Color(149, 149, 149));
        deshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/undo.png"))); // NOI18N
        deshacer.setText("Deshacer");
        deshacer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(deshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnObtenerActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObtenerActualActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnAnterior;
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnObtenerActual;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel btnSiguiente;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel cmbLabelTabla;
    private javax.swing.JLabel cmbLabelTipoSolicitud;
    private javax.swing.JPanel cmbPanelTabla;
    private javax.swing.JPanel cmbPanelTipoSolicitud;
    private javax.swing.JLabel deshacer;
    private javax.swing.JLabel eliminar;
    private javax.swing.JPanel f1;
    private javax.swing.JLabel f11;
    private javax.swing.JLabel f12;
    private javax.swing.JLabel f13;
    private javax.swing.JPanel f2;
    private javax.swing.JLabel f21;
    private javax.swing.JLabel f22;
    private javax.swing.JLabel f23;
    private javax.swing.JPanel f3;
    private javax.swing.JLabel f31;
    private javax.swing.JLabel f32;
    private javax.swing.JLabel f33;
    private javax.swing.JPanel f4;
    private javax.swing.JLabel f41;
    private javax.swing.JLabel f42;
    private javax.swing.JLabel f43;
    private javax.swing.JPanel f5;
    private javax.swing.JLabel f51;
    private javax.swing.JLabel f52;
    private javax.swing.JLabel f53;
    private javax.swing.JPanel f6;
    private javax.swing.JLabel f61;
    private javax.swing.JLabel f62;
    private javax.swing.JLabel f63;
    private javax.swing.JPanel f7;
    private javax.swing.JLabel f71;
    private javax.swing.JLabel f72;
    private javax.swing.JLabel f73;
    private javax.swing.JPanel f8;
    private javax.swing.JLabel f81;
    private javax.swing.JLabel f82;
    private javax.swing.JLabel f83;
    private javax.swing.JLabel info;
    private javax.swing.JTextField inputBuscar;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lupa;
    private javax.swing.JPanel nav;
    private javax.swing.JLabel pagina;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPaginacion;
    private javax.swing.JPanel tabla;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }
    
    public JButton getBtnAtender() {
        return btnAtender;
    }
    
    public JButton getBtnActual() {
        return btnObtenerActual;
    }
    
    public JLabel getBtnEliminar() {
        return eliminar;
    }
    
    public JLabel getBtnDeshacer() {
        return deshacer;
    }
    
    public JLabel getBtnInfo() {
        return info;
    }
    
    public JLabel getBtnBuscar() {
        return lupa;
    }

    public JPanel getTabla() {
        return tabla;
    }
    
    public JLabel[] getCabeceras() {
        JLabel[] cabeceras = {c1,c2,c3};
        return cabeceras;
    }
    
    public JPanel[] getFilas() {
        JPanel[] filas = {f1, f2, f3, f4, f5, f6, f7, f8};
        return filas;
    }
    
    public JLabel[][] getColumnas() {
        JLabel[][] columnas = {
            {f11,f12,f13},
            {f21,f22,f23},
            {f31,f32,f33},
            {f41,f42,f43},
            {f51,f52,f53},
            {f61,f62,f63},
            {f71,f72,f73},
            {f81,f82,f83}
        };
        return columnas;
    }
    
    public JLabel[] getPaginacion() {
        JLabel[] buttons = {pagina, btnAnterior, btnSiguiente};
        return buttons;
    }
    
    public JTextField getInputBuscar() {
        return inputBuscar;
    }
    public JPanel getPanelBuscar() {
        return panelBuscar;
    }
    
    public JTextField getInputNombre() {
        return inputNombre;
    }
    public JPanel getPanelNombre() {
        return panelNombre;
    }
    
    public JPanel getCmbPanelTabla() {
        return cmbPanelTabla;
    }

    public JLabel getCmbLabelTabla() {
        return cmbLabelTabla;
    }
    
     public JPanel getCmbPanelTipoSolicitud() {
        return cmbPanelTipoSolicitud;
    }

    public JLabel getCmbLabelTipoSolicitud() {
        return cmbLabelTipoSolicitud;
    }
    
    public JCheckBox getCheckBox() {
        return checkbox;
    }
}
